### ISSUE TITLE
Cookie policy exception at integration tests

### ISSUE THREAD

**Issue by wallacemariadeandrade** [wallacemariadeandrade/AspNetCoreTodo#9]
Stack trace:

```
C:\Users\Wallace K2 Telecom\source\repos\AspNetCoreTodo\AspNetCoreTodo.IntegrationTests>dotnet test
Execução de teste para C:\Users\Wallace K2 Telecom\source\repos\AspNetCoreTodo\AspNetCoreTodo.IntegrationTests\bin\Debug\netcoreapp2.1\AspNetCoreTodo.IntegrationTests.dll(.NETCoreApp,Version=v2.1)
Ferramenta de Linha de Comando de Execução de Teste da Microsoft (R) Versão 16.7.0
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Iniciando execução de teste, espere...

1 arquivos de teste no total corresponderam ao padrão especificado.
[xUnit.net 00:00:00.77]     AspNetCoreTodo.IntegrationTests.TodoRouteShould.ChallengeAnonymousUser [FAIL]
  X AspNetCoreTodo.IntegrationTests.TodoRouteShould.ChallengeAnonymousUser [1ms]
  Mensagem de erro:
   System.AggregateException : One or more errors occurred. (Could not load file or assembly 'Microsoft.AspNetCore.CookiePolicy, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. O sistema não pode encontrar o arquivo especificado.) (The following constructor parameters did not have matching fixture data: TestFixture fixture)
---- System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.CookiePolicy, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. O sistema não pode encontrar o arquivo especificado.
---- The following constructor parameters did not have matching fixture data: TestFixture fixture
  Rastreamento de pilha:

----- Inner Stack Trace #1 (System.IO.FileNotFoundException) -----
   at AspNetCoreTodo.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at AspNetCoreTodo.IntegrationTests.TestFixture..ctor() in C:\Users\Wallace K2 Telecom\source\repos\AspNetCoreTodo\AspNetCoreTodo.IntegrationTests\TestFixture.cs:line 24 
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----


Falha na Execução de Teste.
Total de testes: 1
     Com falha: 1
Tempo total: 1,5086 Segundos
C:\Program Files\dotnet\sdk\3.1.403\Microsoft.TestPlatform.targets(32,5): error MSB4181: A tarefa "Microsoft.TestPlatform.Build.Tasks.VSTestTask" retornou false, mas não registrou um erro. [C:\Users\Wallace K2 Telecom\source\repos\AspNetCoreTodo\AspNetCoreTodo.IntegrationTests\AspNetCoreTodo.IntegrationTests.csproj]
```

**Comment by wallacemariadeandrade** [comment]
Problem solved by manually including `<PackageReference Include="Microsoft.AspNetCore.App" />` in the project file.
